# Generated by Django 5.2.3 on 2025-07-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.CharField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='NULL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='token',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
